# .github/dependabot.yml
# This file will update both Python packages and GitHub Actions

version: 2
updates:
  
  # Check for Python (pip) updates
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt
    schedule:
      interval: "weekly"
      
  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/" # Location of .github/workflows
    schedule:
      interval: "weekly"
